name: portfolio
description: Portfolio developed in flutter.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.10.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flex_color_scheme: ^8.4.0
  google_fonts: ^8.0.2
  font_awesome_flutter: ^10.12.0
  flutter_riverpod: 3.1.0
  riverpod_annotation: 4.0.0
  collection: ^1.19.1
  url_launcher: ^6.3.2
  url_strategy: ^0.3.0
  intl: ^0.20.2
  easy_localization: ^3.0.8
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  shared_preferences: ^2.5.4
  velocity_x: ^4.3.1
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  custom_lint: ^0.8.1
  riverpod_lint: 3.1.0
  build_runner: ^2.12.2
  riverpod_generator: 4.0.0+1
  freezed: 3.2.3
  json_serializable: 6.11.2
  flutter_native_splash: ^2.4.7
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/translations/

hooks:
  postget:
      - dart run easy_localization:generate -S assets/translations -f keys -O lib/src/localization/generated -o locale_keys.g.dart
      - dart run easy_localization:generate -S assets/translations -f json -O lib/src/localization/generated -o locale_json.g.dart
