name: portfolio
description: Portfolio developed in flutter.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flex_color_scheme: ^7.1.2
  google_fonts: ^4.0.4
  font_awesome_flutter: ^10.4.0
  flutter_riverpod: ^2.3.6
  riverpod_annotation: ^2.1.1
  collection: ^1.17.1
  url_launcher: ^6.1.11
  firebase_core: ^2.14.0
  url_strategy: ^0.2.0
  intl: ^0.18.0
  easy_localization: ^3.0.2
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  shared_preferences: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  custom_lint: ^0.4.0
  riverpod_lint: ^1.3.2
  build_runner: ^2.4.5
  riverpod_generator: ^2.2.3
  freezed: ^2.4.1
  json_serializable: ^6.7.1
  flutter_native_splash: ^2.3.1
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/translations/
